name: CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  forkless-test:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: pythons deps
      run: python -m pip install pytest pexpect
    - name: macos deps
      if: ${{ contains(matrix.os, 'macos') }}
      run: brew install gnu-sed
    - name: cmake
      uses: threeal/cmake-action@v2.0.0
      with:
        build-dir: build
    - name: test
      run: FORKLESS_PATH=./build/forkless pytest -v ./tests/test_forkless.py
  tvm-test:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: test
      run: make test -j && ./test_tvm
