name: CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  forkless-test:
      runs-on: ubuntu-22.04
      steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: pythons deps
        run: python -m pip install pytest pexpect
      - name: make
        run: make
      - name: test
        run: pytest -v ./test_forkless.py
  tvm-test:
      runs-on: ubuntu-22.04
      steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: test
        run: make test && ./test_tvm